setup.py: add content type for MD description
PyPI now requires content type set for descriptions, otherwise it fails
with the following error:

    HTTPError: 400 Client Error: The description failed to render in the default format of reStructuredText. See https://pypi.org/help/#description-content-type for more information. for url: https://upload.pypi.org/legacy/

Ref #102